version: "3.9"

services:
  web:
    build: .
    container_name: nexus_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:15
    container_name: nexus_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - nexus_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: nexus_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"  # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  worker:
    build: .
    container_name: nexus_worker
    command: celery -A nexus worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq

volumes:
  nexus_db_data:
